<?php
/**
 * This file is part of HumanResources plugin for FacturaScripts.
 * FacturaScripts Copyright (C) 2015-2025 Carlos Garcia Gomez <carlos@facturascripts.com>
 * HumanResources Copyright (C) 2018-2025 Jose Antonio Cuello Principal <yopli2000@gmail.com>
 *
 * This program and its files are under the terms of the license specified in the LICENSE file.
 */
namespace FacturaScripts\Plugins\HumanResources\Model;

use FacturaScripts\Core\Model\Base\ModelTrait;
use FacturaScripts\Dinamic\Model\Asiento;
use FacturaScripts\Dinamic\Model\PayRoll;
use FacturaScripts\Plugins\HumanResources\Lib\HumanResources\ModelExtended;

/**
 * List of accounting entries generated by the payment of payroll to employees
 *
 * @author Jose Antonio Cuello Principal <yopli2000@gmail.com>
 */
class PayRollAccounting extends ModelExtended
{

    use ModelTrait;

    /**
     * Date of creation of the accounting
     *
     * @var string
     */
    public $creationdate;

    /**
     * Link to asiento model
     *
     * @var integer
     */
    public $identry;

    /**
     * Link to payroll model
     *
     * @var integer
     */
    public $idpayroll;

    /**
     * Reset the values of all model properties.
     */
    public function clear()
    {
        parent::clear();
        $this->creationdate = date('d-m-Y');
    }

    /**
     * Remove the model data from the database.
     *
     * @return bool
     */
    public function delete(): bool
    {
        $entry = $this->getAsiento();
        $entry->editable = true;

        $newTransation = false === self::$dataBase->inTransaction() && self::$dataBase->beginTransaction();
        try {
            if (false === $entry->delete() || false === parent::delete()) {
                return false;
            }

            if ($newTransation) {
                self::$dataBase->commit();
            }
        } finally {
            if ($newTransation && self::$dataBase->inTransaction()) {
                self::$dataBase->rollback();
            }
        }
        return true;
    }

    /**
     * Returns the accounting entry associated with the posting of payroll.
     *
     * @return Asiento
     */
    public function getAsiento(): Asiento
    {
        if (empty($this->identry)) {
            $this->loadFromCode($this->id);
        }

        $entry = new Asiento();
        $entry->loadFromCode($this->identry);
        return $entry;
    }

    /**
     * This function is called when creating the model table. Returns the SQL
     * that will be executed after the creation of the table. Useful to insert values
     * default.
     *
     * @return string
     */
    public function install(): string
    {
        new Asiento();
        new PayRoll();
        parent::install();

        return '';
    }

    /**
     * This function is called when creating the model table. Returns the SQL
     * that will be executed after the creation of the table. Useful to insert values
     * default.
     *
     * @return string
     */
    public static function tableName(): string
    {
        return 'rrhh_payrollaccounting';
    }
}
