<?php
/**
 * This file is part of HumanResources plugin for FacturaScripts.
 * FacturaScripts Copyright (C) 2015-2025 Carlos Garcia Gomez <carlos@facturascripts.com>
 * HumanResources Copyright (C) 2018-2025 Jose Antonio Cuello Principal <yopli2000@gmail.com>
 *
 * This program and its files are under the terms of the license specified in the LICENSE file.
 */
namespace FacturaScripts\Plugins\HumanResources\Model\Join;

use FacturaScripts\Dinamic\Model\Base\JoinModel;
use FacturaScripts\Dinamic\Model\PayRollAccounting;

/**
 * Auxiliary model to obtain the data of the accounting entries
 * generated by the payment of a payroll.
 *
 * @author Jose Antonio Cuello Principal <yopli2000@gmail.com>
 */
class PayRollAccountingSummary extends JoinModel
{

    /**
     * Constructor and class initializer.
     *
     * @param array $data
     */
    public function __construct($data = array())
    {
        parent::__construct($data);
        $this->setMasterModel(new PayRollAccounting);

        if (!self::$dataBase->tableExists('rrhh_payrollaccounting')) {
            new PayRollAccounting();
        }
    }

    /**
     * Returns the url where to see / modify the data.
     *
     * @param string $type
     * @param string $list
     *
     * @return string
     */
    public function url(string $type = 'auto', string $list = 'List'): string
    {
        if (empty($this->identry)) {
            return '';
        }
        return 'EditAsiento?code=' . $this->identry;
    }

    /**
     * List of fields or columns to select clausule
     */
    protected function getFields(): array
    {
        return [
            'id' => 'rrhh_payrollaccounting.id',
            'idpayroll' => 'rrhh_payrollaccounting.idpayroll',
            'identry' => 'rrhh_payrollaccounting.identry',
            'creationdate' => 'rrhh_payrollaccounting.creationdate',
            'canal' => 'asientos.canal',
            'idasiento' => 'asientos.idasiento',
            'codejercicio' => 'asientos.codejercicio',
            'concepto' => 'asientos.concepto',
            'numero' => 'asientos.numero',
            'fecha' => 'asientos.fecha',
            'importe' => 'asientos.importe',
            'diario' => 'diarios.descripcion'
        ];
    }

    /**
     * List of tables related to from clausule
     */
    protected function getSQLFrom(): string
    {
        return 'rrhh_payrollaccounting'
            . ' INNER JOIN asientos ON asientos.idasiento = rrhh_payrollaccounting.identry'
            . ' LEFT JOIN diarios ON diarios.iddiario = asientos.iddiario';
    }

    /**
     * List of tables required for the execution of the view.
     */
    protected function getTables(): array
    {
        return [
            'rrhh_payrollaccounting',
            'asientos',
            'diarios'
        ];
    }
}
