<?php
/**
 * This file is part of DocumentosRecurrentes plugin for FacturaScripts.
 * FacturaScripts         Copyright (C) 2015-2021 Carlos Garcia Gomez <carlos@facturascripts.com>
 * DocumentosRecurrentes  Copyright (C) 2020-2021 Jose Antonio Cuello Principal <yopli2000@gmail.com>
 *
 * This program and its files are under the terms of the license specified in the LICENSE file.
 */
namespace FacturaScripts\Plugins\DocumentosRecurrentes\Lib\DocumentosRecurrentes;

use FacturaScripts\Core\Base\ToolBox;
use FacturaScripts\Dinamic\Lib\Email\NewMail;
use FacturaScripts\Dinamic\Lib\ExportManager;
use FacturaScripts\Dinamic\Model\EmailNotification;

/**
 * Description of Email
 *
 * @author Jose Antonio Cuello  <yopli2000@gmail.com>
 */
class DocRecurringEmail {

    private const NOTIFICATION_ID = 'DocRecurring';

    /**
     * Document generated.
     *
     * @var BusinessDocument
     */
    private $document;

    /**
     * Class responsible for sending emails.
     *
     * @var NewMail
     */
    private $newMail = null;

    /**
     * format of the email to send.
     *
     * @var EmailNotification
     */
    private $notification = null;

    /**
     * Subject to whom the document belongs.
     *
     * @var Subject
     */
    private $subject = null;

    /**
     * Class constructor.
     *
     * @param BusinessDocument $document
     */
    public function __construct(&$document)
    {
        $this->document = $document;
    }

    /**
     * Send a recurring document generated by mail.
     *   - Create the necessary structures.
     *   - Create the PDF of the document in a temporary folder.
     *   - Send the mail with PDF attached.
     *   - Remove PDF of temporary folder.
     *
     * @return bool
     */
    public function sendMail(): bool
    {
        if (false === $this->initData()) {
            return false;
        }

        $fileName = $this->document->codigo . '_' . time() . '.pdf';
        $filePath = \FS_FOLDER . '/MyFiles/' . $fileName;
        if (false === $this->saveDocumentPDF($filePath)) {
            return false;
        }

        $this->newMail->addAddress($this->subject->email, $this->subject->nombre);
        $this->newMail->title = $this->getText($this->notification->subject);
        $this->newMail->text = $this->getText($this->notification->body);

        $this->newMail->addAttachment($filePath, $fileName);
        $result = $this->newMail->send();

        if (file_exists($filePath)) {
            unlink($filePath);
        }

        return $result;
    }

    /**
     * Returns the structure for substitution macros in the mail texts.
     *
     * @return array
     */
    private function getParams(): array
    {
        return [
            'document' => $this->document->codigo,
            'date' => $this->document->fecha,
            'total' => $this->document->total,
            'email' => $this->subject->email,
            'name' => $this->subject->nombre,
            'namefiscal' => $this->subject->razonsocial,
            'type' => $this->toolBox()->i18n()->trans($this->document->modelClassName() . '-min'),
        ];
    }

    /**
     * Performs macro substitution on the indicated text.
     *
     * @param string $text
     * @return string
     */
    private function getText(string $text): string
    {
        foreach ($this->getParams() as $key => $value) {
            $text = str_replace('{' . $key . '}', $value, $text);
        }

        return $text;
    }

    /**
     * Create the necessary structures.
     * Report the error if you can't.
     *   - NewMail
     *   - EmailNotification
     *   - DocumentSubject [Client|Supplier]
     *
     * @return bool
     */
    private function initData(): bool
    {
        $this->newMail = new NewMail();
        if (false === $this->newMail->canSendMail()) {
            $this->toolBox()->i18nLog()->warning('email-not-configured');
            return false;
        }

        $this->notification = new EmailNotification();
        if (false == $this->notification->loadFromCode(self::NOTIFICATION_ID)) {
            $this->toolBox()->i18nLog()->warning('notification-not-configured');
            return false;
        }

        $this->subject = $this->document->getSubject();
        if (empty($this->subject->email)) {
            $this->toolBox()->i18nLog()->warning('mail-field-empty');
            return false;
        }

        return true;
    }

    /**
     * Generates a PDF of the document and saves it
     * with the indicated name and path.
     *
     * @param string $fileName
     * @return bool
     */
    private function saveDocumentPDF(string $fileName): bool
    {
        $exportManager = new ExportManager();
        $exportManager->newDoc('PDF', $this->document->codigo);
        $exportManager->addBusinessDocPage($this->document);
        $pdf = $exportManager->getDoc();
        if (empty($pdf)) {
            $this->toolBox()->i18nLog()->error('pdf-empty');
            return false;
        }

        if (false === \file_put_contents($fileName, $pdf)) {
            $this->toolBox()->i18nLog()->error('folder-not-writable');
            return false;
        }
        return true;
    }

    /**
     *
     * @return ToolBox
     */
    private function toolBox()
    {
        return new ToolBox();
    }
}
